_base_model: &base_model
    base: id_resource
    key: id
    admin_roles: [ organization-admin ]
    view_roles: [ organization-auditor ]
    priority: 60

roles:
    organization-admin: Organization administrator (full privileges over all organizations)
    organization-auditor: Organization auditor (viewing privileges over all organizations)

models:
    location:
        <<: *base_model
        id_fields: [ city, state, zipcode ]
        name_field: false
        display: "<city>, <state> <zipcode>"
        fields:
            city:
                type: string
            state:
                type: string
            zipcode:
                type: string
                options:
                    max_length: 20

    organization:
        <<: *base_model
        display: "<name>"
        mixins: [ location_optional ]
        priority: 65
        fields:
            parent:
                type: foreign_key
                options:
                    related_data_name: organization
