# Generated by Django 4.0.2 on 2022-02-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=256)),
                ('city', models.CharField(default=None, max_length=256, null=True)),
                ('state', models.CharField(default=None, max_length=256, null=True)),
                ('zipcode', models.CharField(default=None, max_length=10, null=True)),
                ('parent', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_relation', to='organization.organization')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'organizations_organization',
                'ordering': ['id'],
                'abstract': False,
                'unique_together': {('name',)},
            },
        ),
    ]
