# Generated by Django 4.1.2 on 2022-11-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['id'], 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
    ]
